# Site settings
title: "Mohamed chiheb Resume "
description: "Mohamed chiheb ben jemaa, online resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mohamed chiheb ben jemaa"
resume_title:                   "DevOps & Full Stack developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mc.benjemaa@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+216 23388096"
resume_contact_address:         "cite khadhra, Tunis"

resume_header_contact_info:     "cite khadhra, Tunis • +21623388096 • mc.benjemaa@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> DevOps & Fullstack developer with over 2 years of experience.

<ul> <li>Main interests: JAVA/JEE, Opensource, cloud-native, kuberentes.. </li>

<li>CNCF speaker: https://www.cncf.io/speaker/meddchiheb/ </li>

<li>kuberentes community Member: https://github.com/medmedchiheb</li></ul>

  </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/medmedchiheb"
  resume_twitter_url:           "http://twitter.com/mcbenjemaa"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mohamed-chiheb-ben-jemaa-5b6357113/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://medmedchiheb.github.io/resume/"
  resume_medium_url:            "https://medmedchiheb.github.io/resume/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman
